package com.example.administrator.myapplication.JSON;

import java.util.List;

public class DetailBean {
    public RatingBean rating;
    public int reviews_count;
    public int wish_count;
    public String original_title;
    public List<String> blooper_urls;
    public int collect_count;
    public UrlBean images;
    public String douban_site;
    public String year;
    public List<Commentbean> popular_comments;
    public String alt;
    public String id;
    public String mobile_url;
    public int photos_count;
    public String pubdate;
    public String title;
    public boolean has_video;
    public String share_url;
    public List<String> languages;
    public String schedule_url;
    public List<CastBean> writers;
    public List<String> pubdates;
    public String website;
    public List<String> tags;
    public boolean has_schedule;
    public List<String> durations;
    public List<String> genres;
    public List<VideoBean> trailers;
    public List<String> trailer_urls;
    public boolean has_ticket;
    public List<VideoBean> bloopers;
    public List<String> clip_urls;
    public List<CastBean> casts;
    public List<String> countries;
    public String mainland_pubdate;
    public List<PhotoBean> photos;
    public String summary;
    public List<VideoBean> clips;
    public String subtype;
    public List<CastBean> directors;
    public int comments_count;
    public List<ReviewBean> popular_reviews;
    public int ratings_count;
    public List<String> aka;
}
